name: '[SERV] Assign Code Reviewers'
on:
  pull_request:
    types: [labeled]

  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      labels:
        required: true
        type: string

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - id: params
        name: Set PR number and reviewer
        run: |
          pr_number="${{ inputs.pr_number }}"
          labels="${{ inputs.labels }}"
          reviewer=""
          if [[ "$labels" == *"Readme"* ]]; then
            reviewer="alldayalone"
          fi
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "reviewer=$reviewer" >> $GITHUB_OUTPUT
      - name: Assign code reviewers
        if: steps.params.outputs.reviewer != ''
        run: |
          gh pr edit ${{ steps.params.outputs.pr_number }} --add-assignee ${{ steps.params.outputs.reviewer }}
          gh pr edit ${{ steps.params.outputs.pr_number }} --add-reviewer ${{ steps.params.outputs.reviewer }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 